# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5770f6fd99e5ee7acba45a76063e267352780d3b1819ea2f159e44438278b7e3d1ae77adbd5226bd130a5daba73693b72dc5b8fb3948543f73af55cfa265e77

test:
  secret_key_base: 59735a9608cdb54e78eec1130fb4fe953484e7e9b438a0a3971361b9c5e24f12dc18472d8eb308adfed954cc6faa5b535c3eb82ff7fc551fed382a65a114e8f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
